#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
#spring.datasource.username = BID
#spring.datasource.password = BID

mybatis.mapper-locations: =/mapper/**/*.xml
  
# jdbc log4jdbc로 변경
spring:
  datasource:
  driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
  username : BID
  password : BID

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off