/*---------------------------------------------
-- 오브젝트명: TB_BID_DETAIL
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE TB_BID_DETAIL
(
    BID_ID                NVARCHAR2(30)  NOT NULL,
    BID_GUBN_CODE         NVARCHAR2(2)   NOT NULL,
    GURAE_TIME_GUBN_CODE  NVARCHAR2(3)   NOT NULL,
    GURAE_TIME            NVARCHAR2(2)   NOT NULL,
    GUBN_CODE             NVARCHAR2(2)   NOT NULL,
    GUBN_NAME             NVARCHAR2(30),
    SUBMIT_VAL            NVARCHAR2(10)
);

COMMENT ON TABLE TB_BID_DETAIL IS '입찰디테일';

COMMENT ON COLUMN TB_BID_DETAIL.BID_ID IS '입찰식별아이디';

COMMENT ON COLUMN TB_BID_DETAIL.BID_GUBN_CODE IS '입찰구분코드';

COMMENT ON COLUMN TB_BID_DETAIL.GURAE_TIME_GUBN_CODE IS '거래시간구분코드';

COMMENT ON COLUMN TB_BID_DETAIL.GURAE_TIME IS '거래시간';

COMMENT ON COLUMN TB_BID_DETAIL.GUBN_CODE IS '구분코드';

COMMENT ON COLUMN TB_BID_DETAIL.GUBN_NAME IS '구분명';

COMMENT ON COLUMN TB_BID_DETAIL.SUBMIT_VAL IS '제출값';

ALTER TABLE TB_BID_DETAIL ADD CONSTRAINT TB_BID_DETAIL_PK PRIMARY KEY (BID_ID,BID_GUBN_CODE,GURAE_TIME_GUBN_CODE,GURAE_TIME,GUBN_CODE);

/*---------------------------------------------
-- 오브젝트명: TB_BID_MASTER
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE TB_BID_MASTER
(
    BID_ID                 NVARCHAR2(30)  NOT NULL,
    GURAE_DATE             NVARCHAR2(8)   NOT NULL,
    BALJUNKI_COMPANY_CODE  NVARCHAR2(10)  NOT NULL,
    BALJUNKI_GUBN_CODE     NVARCHAR2(2)   NOT NULL,
    BALJUNKI_ID            NVARCHAR2(21)  NOT NULL,
    TEUKI_REMK             NVARCHAR2(20),
    BALJUNKI_COMPANY_SIGN  NVARCHAR2(30),
    SUBMIT_DATE            NVARCHAR2(8),
    SUBMIT_TIME            NVARCHAR2(4),
    SUBMIT_EMPL_NUMB       NVARCHAR2(30),
    SUBMIT_EMPL_SIGN       NVARCHAR2(30)
);

COMMENT ON TABLE TB_BID_MASTER IS '입찰마스터';

COMMENT ON COLUMN TB_BID_MASTER.BID_ID IS '입찰식별아이디';

COMMENT ON COLUMN TB_BID_MASTER.GURAE_DATE IS '거래일날짜';

COMMENT ON COLUMN TB_BID_MASTER.BALJUNKI_COMPANY_CODE IS '발전회사코드';

COMMENT ON COLUMN TB_BID_MASTER.BALJUNKI_GUBN_CODE IS '발전기구분코드';

COMMENT ON COLUMN TB_BID_MASTER.BALJUNKI_ID IS '발전기식별번호';

COMMENT ON COLUMN TB_BID_MASTER.TEUKI_REMK IS '특이사항';

COMMENT ON COLUMN TB_BID_MASTER.BALJUNKI_COMPANY_SIGN IS '발전회사서명';

COMMENT ON COLUMN TB_BID_MASTER.SUBMIT_DATE IS '날짜';

COMMENT ON COLUMN TB_BID_MASTER.SUBMIT_TIME IS '접수시각';

COMMENT ON COLUMN TB_BID_MASTER.SUBMIT_EMPL_NUMB IS '접수자사번';

COMMENT ON COLUMN TB_BID_MASTER.SUBMIT_EMPL_SIGN IS '접수자서명';

ALTER TABLE TB_BID_MASTER ADD CONSTRAINT TB_BID_MASTER_PK PRIMARY KEY (BID_ID);

/*---------------------------------------------
-- 오브젝트명: TB_BID_TEUKSEONG
-- 상태: VALID
---------------------------------------------*/
CREATE TABLE TB_BID_TEUKSEONG
(
    BID_ID                      NVARCHAR2(30)  NOT NULL,
    TEUKSEONG_BUNRYU_CODE       NVARCHAR2(2)   NOT NULL,
    TEUKSEONG_BUNRYU_GUBN_CODE  NVARCHAR2(2)   NOT NULL,
    TEUKSEONG_BUNRYU_GUBN_NAME  NVARCHAR2(13),
    SUBMIT_VAL                  NVARCHAR2(5),
    UPDATE_REMK                 NVARCHAR2(20)
);

COMMENT ON TABLE TB_BID_TEUKSEONG IS '입찰특성';

COMMENT ON COLUMN TB_BID_TEUKSEONG.BID_ID IS '입찰식별아이디';

COMMENT ON COLUMN TB_BID_TEUKSEONG.TEUKSEONG_BUNRYU_CODE IS '특성분류코드';

COMMENT ON COLUMN TB_BID_TEUKSEONG.TEUKSEONG_BUNRYU_GUBN_CODE IS '특성분류구분코드';

COMMENT ON COLUMN TB_BID_TEUKSEONG.TEUKSEONG_BUNRYU_GUBN_NAME IS '특성분류구분명';

COMMENT ON COLUMN TB_BID_TEUKSEONG.SUBMIT_VAL IS '제출값';

COMMENT ON COLUMN TB_BID_TEUKSEONG.UPDATE_REMK IS '변경사유';

ALTER TABLE TB_BID_TEUKSEONG ADD CONSTRAINT TB_BID_TEUKSEONG_PK PRIMARY KEY (BID_ID,TEUKSEONG_BUNRYU_CODE,TEUKSEONG_BUNRYU_GUBN_CODE);